# Generated by Django 5.1.6 on 2025-02-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('business', 'Business'), ('education', 'Education')], default='tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default_event.jpg', upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
