# Generated by Django 5.1.6 on 2025-02-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_created_at_remove_event_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('tech', 'Tech'), ('business', 'Business'), ('education', 'Education')], default='tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default_event.jpg', null=True, upload_to='event_images/'),
        ),
    ]
